apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service
spec:
  selector:
    app: myapp
  ports:
    - name: http
      port: 80 # Service port
      targetPort: 80 # Container port
      nodePort: 31231 # Nodeport
  type: NodePort
