apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-nodeport-service
  labels:
    app: frontend-nginxapp
    tier: frontend

spec:
  selector:
    app: frontend-nginxapp
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 31234
  type: NodePort
